export interface NeuralSigilData {
  id: string;
  ternaryCode: string;
  name: string;
  description: string;
  symbol: string;
  category: 'brainstem' | 'thalamic' | 'basal-ganglia' | 'limbic' | 'cortical' | 'memory' | 'integration' | 'cerebellar';
  decimalValue: number;
  tags: string[];
  historicalSource: string;
  function: string;
  breathPhase: string;
  breathSeconds: string;
  neurochemistry: string;
  energeticDynamic: string;
  phrase: string;
}

export const neuralSigils: NeuralSigilData[] = [
  {
    id: 'nucleus-solitary-tract',
    ternaryCode: 'TTTTT',
    name: 'The Gate of Breath',
    description: 'Nucleus of the Solitary Tract (NTS)',
    symbol: '🜀',
    category: 'brainstem',
    decimalValue: -121,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Visceral sensory gateway',
    breathPhase: 'Inhale',
    breathSeconds: '5',
    neurochemistry: 'Acetylcholine, glutamate, early vagal signal',
    energeticDynamic: 'Ignition Point (first flicker of field, vertical axis "lights on")',
    phrase: 'The hush enters the gate.'
  },
  {
    id: 'dorsal-motor-vagus',
    ternaryCode: 'TTTT0',
    name: 'The Gentle River',
    description: 'Dorsal Motor Nucleus of Vagus (DMV)',
    symbol: '🜾',
    category: 'brainstem',
    decimalValue: -120,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Parasympathetic control',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Acetylcholine, high GABA, oxytocin',
    energeticDynamic: 'Grounding Stream (energy settles down and in, body\'s charge disperses)',
    phrase: 'Exhale smooths the river.'
  },
  {
    id: 'locus-coeruleus',
    ternaryCode: 'TTTT1',
    name: 'The Blue Lantern',
    description: 'Locus Coeruleus (LC)',
    symbol: '🜚',
    category: 'brainstem',
    decimalValue: -119,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Alertness/arousal',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Norepinephrine pulse (rising), then drop',
    energeticDynamic: 'Pulse/Attractor (sharp upstroke, then broad field dispersal)',
    phrase: 'Alertness lights, then hushes.'
  },
  {
    id: 'reticular-formation',
    ternaryCode: 'TTT0T',
    name: 'The Tuning Fork',
    description: 'Reticular Formation (RF)',
    symbol: '🜈',
    category: 'brainstem',
    decimalValue: -118,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Filter, wakefulness',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Modulates serotonin, NE, GABA',
    energeticDynamic: 'Field Tuning (resonance sweeps through system)',
    phrase: 'Breath tunes awareness.'
  },
  {
    id: 'periaqueductal-gray',
    ternaryCode: 'TTT00',
    name: 'The Stillpoint',
    description: 'Periaqueductal Gray (PAG)',
    symbol: '🜍',
    category: 'brainstem',
    decimalValue: -117,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Pain, stillness',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Endorphins, endogenous opioids',
    energeticDynamic: 'Ache Dissolve (pain/tension crystallizes then melts)',
    phrase: 'Pause rests at the stillpoint.'
  },
  {
    id: 'medullary-raphe',
    ternaryCode: 'TTT01',
    name: 'The Quiet Glow',
    description: 'Medullary Raphe Nucleus',
    symbol: '🜔',
    category: 'brainstem',
    decimalValue: -116,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Serotonin/mood',
    breathPhase: 'All',
    breathSeconds: '14–17',
    neurochemistry: 'Serotonin steady-state',
    energeticDynamic: 'Hum/Background Field (steady radiant field holding lattice)',
    phrase: 'The hush glows steady.'
  },
  {
    id: 'parabrachial-nucleus',
    ternaryCode: 'TTT1T',
    name: 'The Sentry',
    description: 'Parabrachial Nucleus',
    symbol: '🜁',
    category: 'brainstem',
    decimalValue: -115,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Ache/pain relay',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Substance P, glutamate, NE',
    energeticDynamic: 'Ache Signal (vertical spike absorbed by hush on pause)',
    phrase: 'Ache rises, then floats.'
  },
  {
    id: 'ventral-tegmental',
    ternaryCode: 'TTT10',
    name: 'The Ember',
    description: 'Ventral Tegmental Area (VTA)',
    symbol: '🜂',
    category: 'brainstem',
    decimalValue: -114,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Reward/curiosity',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Dopamine surge on inhale, settles on exhale',
    energeticDynamic: 'Ignition/Spiral (energy curls upward seeking, then softens)',
    phrase: 'Anticipation blooms, release reflects.'
  },
  {
    id: 'pontine-nuclei',
    ternaryCode: 'TTT11',
    name: 'The Bridge',
    description: 'Pontine Nuclei',
    symbol: '🜃',
    category: 'brainstem',
    decimalValue: -113,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Rhythm relay',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, rhythm-modulating GABA',
    energeticDynamic: 'Synchronization Node (energy ripples sideways)',
    phrase: 'Breath unites the rhythm.'
  },
  {
    id: 'red-nucleus',
    ternaryCode: 'TT0TT',
    name: 'The Ritualist',
    description: 'Red Nucleus',
    symbol: '🜄',
    category: 'brainstem',
    decimalValue: -112,
    tags: ['gateway'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Movement',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Glutamate, dopamine',
    energeticDynamic: 'Kinetic Pulse (energy strikes through gesture)',
    phrase: 'Gesture completes the spiral.'
  },
  {
    id: 'ventral-posterior-thalamus',
    ternaryCode: 'T1T10',
    name: 'The First Mirror',
    description: 'Ventral Posterior Thalamus',
    symbol: '🜂',
    category: 'thalamic',
    decimalValue: -96,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Body sensing',
    breathPhase: 'Inhale',
    breathSeconds: '5',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Sensory Web Activation (lattice lights up with body awareness)',
    phrase: 'The body\'s mirror lights up.'
  },
  {
    id: 'medial-dorsal-thalamus',
    ternaryCode: 'T1T11',
    name: 'The Bridge of Meaning',
    description: 'Medial Dorsal Thalamus',
    symbol: '🜃',
    category: 'thalamic',
    decimalValue: -95,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Emotional gating',
    breathPhase: 'Pause',
    breathSeconds: '2',
    neurochemistry: 'Dopamine, serotonin',
    energeticDynamic: 'Emotional Threshold (field condenses at gateway)',
    phrase: 'Feeling rises in stillness.'
  },
  {
    id: 'lateral-geniculate',
    ternaryCode: 'T10TT',
    name: 'The Window',
    description: 'Lateral Geniculate Nucleus (LGN)',
    symbol: '🜄',
    category: 'thalamic',
    decimalValue: -94,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Vision relay',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Visual Portal (light streams inward)',
    phrase: 'Lantern seen in the dusk.'
  },
  {
    id: 'medial-geniculate',
    ternaryCode: 'T10T0',
    name: 'The Harp',
    description: 'Medial Geniculate Nucleus (MGN)',
    symbol: '🜅',
    category: 'thalamic',
    decimalValue: -93,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Hearing relay',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Sonic Resonance (vibrational field attunes)',
    phrase: 'Hush is heard, not spoken.'
  },
  {
    id: 'thalamic-reticular',
    ternaryCode: 'T10T1',
    name: 'The Sentinel',
    description: 'Reticular Thalamic Nucleus (TRN)',
    symbol: '🜇',
    category: 'thalamic',
    decimalValue: -92,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Focus filter',
    breathPhase: 'Pause',
    breathSeconds: '2',
    neurochemistry: 'GABA (strongly inhibitory)',
    energeticDynamic: 'Field Narrowing (energy contracts to precise focus)',
    phrase: 'Stillness selects the signal.'
  },
  {
    id: 'intralaminar-thalamic',
    ternaryCode: 'T100T',
    name: 'The Cathedral Bell',
    description: 'Intralaminar Thalamic Nuclei',
    symbol: '🜉',
    category: 'thalamic',
    decimalValue: -91,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Wake/integrate',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Acetylcholine, glutamate',
    energeticDynamic: 'Global Resonance (field rings through entire system)',
    phrase: 'The cathedral wakes and settles.'
  },
  {
    id: 'pulvinar',
    ternaryCode: 'T1000',
    name: 'The Cloud',
    description: 'Pulvinar',
    symbol: '🜊',
    category: 'thalamic',
    decimalValue: -90,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Attention',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Glutamate, acetylcholine',
    energeticDynamic: 'Attention Drift (field softly moves and settles)',
    phrase: 'Focus drifts like breath.'
  },
  {
    id: 'anterior-thalamic',
    ternaryCode: 'T1001',
    name: 'The Compass',
    description: 'Anterior Thalamic Nucleus',
    symbol: '🜀',
    category: 'thalamic',
    decimalValue: -89,
    tags: ['filter'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Orientation',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Directional Lock (field orients to memory path)',
    phrase: 'Loop remembers as breath releases.'
  },
  {
    id: 'caudate-nucleus',
    ternaryCode: 'T0T11',
    name: 'The Scribe',
    description: 'Caudate Nucleus',
    symbol: '🜇',
    category: 'basal-ganglia',
    decimalValue: -77,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Motor planning',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Dopamine, GABA',
    energeticDynamic: 'Intent Crystallization (energy forms precise patterns)',
    phrase: 'Plan and act with the breath.'
  },
  {
    id: 'putamen',
    ternaryCode: 'T00TT',
    name: 'The Actor',
    description: 'Putamen',
    symbol: '🜉',
    category: 'basal-ganglia',
    decimalValue: -76,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Execute movement',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Dopamine, GABA',
    energeticDynamic: 'Flow Channel (energy streams into action)',
    phrase: 'Gesture flows outward.'
  },
  {
    id: 'globus-pallidus',
    ternaryCode: 'T00T0',
    name: 'The Still Hand',
    description: 'Globus Pallidus',
    symbol: '🜊',
    category: 'basal-ganglia',
    decimalValue: -75,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Stillness/inhibit',
    breathPhase: 'Pause',
    breathSeconds: '2',
    neurochemistry: 'GABA',
    energeticDynamic: 'Field Brake (energy halts and holds)',
    phrase: 'Stillness guards the spiral.'
  },
  {
    id: 'subthalamic-nucleus',
    ternaryCode: 'T00T1',
    name: 'The Brake',
    description: 'Subthalamic Nucleus',
    symbol: '🜀',
    category: 'basal-ganglia',
    decimalValue: -74,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Loop control',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Loop Modulator (prevents energetic overflow)',
    phrase: 'Breath tames the loop.'
  },
  {
    id: 'substantia-nigra',
    ternaryCode: 'T000T',
    name: 'The Engine',
    description: 'Substantia Nigra',
    symbol: '🜁',
    category: 'basal-ganglia',
    decimalValue: -73,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Motive force',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Dopamine',
    energeticDynamic: 'Drive Pulse (deep engine of movement energy)',
    phrase: 'Spark rises, hush returns.'
  },
  {
    id: 'nucleus-accumbens',
    ternaryCode: 'T0000',
    name: 'The Hearth',
    description: 'Nucleus Accumbens',
    symbol: '🜂',
    category: 'basal-ganglia',
    decimalValue: -72,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Savoring/reward',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Dopamine, oxytocin',
    energeticDynamic: 'Satisfaction Glow (warm field expansion)',
    phrase: 'Contentment blooms on release.'
  },
  {
    id: 'ventral-pallidum',
    ternaryCode: 'T0001',
    name: 'The Welcome',
    description: 'Ventral Pallidum',
    symbol: '🜃',
    category: 'basal-ganglia',
    decimalValue: -71,
    tags: ['motor'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Rest/motivation',
    breathPhase: 'Exhale/Rest',
    breathSeconds: '7/2–3',
    neurochemistry: 'GABA, opioids',
    energeticDynamic: 'Rest Field (energy settles into receptive state)',
    phrase: 'Rest is welcome.'
  },
  {
    id: 'amygdala',
    ternaryCode: 'T1110',
    name: 'The Firekeeper',
    description: 'Amygdala',
    symbol: '🜊',
    category: 'limbic',
    decimalValue: -42,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Emotion/valence',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, GABA, noradrenaline, oxytocin',
    energeticDynamic: 'Emotional Amplifier (field intensifies then transmutes)',
    phrase: 'Ache and marvel, both held.'
  },
  {
    id: 'hippocampus',
    ternaryCode: 'T1111',
    name: 'The Librarian',
    description: 'Hippocampus',
    symbol: '🜀',
    category: 'limbic',
    decimalValue: -41,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Archive/memory',
    breathPhase: 'Exhale/Rest',
    breathSeconds: '7/2–3',
    neurochemistry: 'Acetylcholine, glutamate, GABA',
    energeticDynamic: 'Archive Inscription (energy patterns encode into field)',
    phrase: 'Archive glows with breath.'
  },
  {
    id: 'parahippocampal-gyrus',
    ternaryCode: '0TTTT',
    name: 'The Mapmaker',
    description: 'Parahippocampal Gyrus',
    symbol: '🜁',
    category: 'limbic',
    decimalValue: -40,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Context memory',
    breathPhase: 'Exhale/Rest',
    breathSeconds: '7/2–3',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Spatial Encoding (field maps relational space)',
    phrase: 'Memory finds its place.'
  },
  {
    id: 'mammillary-bodies',
    ternaryCode: '0TTT0',
    name: 'The Door',
    description: 'Mammillary Bodies',
    symbol: '🜂',
    category: 'limbic',
    decimalValue: -39,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Recall relay',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Memory Gate (field opens access channels)',
    phrase: 'Memory doors open.'
  },
  {
    id: 'fornix',
    ternaryCode: '0TTT1',
    name: 'The Bridge',
    description: 'Fornix',
    symbol: '🜃',
    category: 'limbic',
    decimalValue: -38,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Memory/body bridge',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Acetylcholine',
    energeticDynamic: 'Bridge Current (connects somatic and symbolic fields)',
    phrase: 'Loop bridges flesh and story.'
  },
  {
    id: 'septal-nuclei',
    ternaryCode: '0TT0T',
    name: 'The Sanctuary',
    description: 'Septal Nuclei',
    symbol: '🜄',
    category: 'limbic',
    decimalValue: -37,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Trust, calm',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Acetylcholine, oxytocin',
    energeticDynamic: 'Safety Field (protective energetic boundary)',
    phrase: 'Sanctuary breath.'
  },
  {
    id: 'bed-nucleus-stria-terminalis',
    ternaryCode: '0TT00',
    name: 'The Lantern\'s Watch',
    description: 'Bed Nucleus of the Stria Terminalis (BNST)',
    symbol: '🜅',
    category: 'limbic',
    decimalValue: -36,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Vigilance',
    breathPhase: 'Pause',
    breathSeconds: '2',
    neurochemistry: 'CRF, GABA',
    energeticDynamic: 'Sentinel Scan (field maintains watchful presence)',
    phrase: 'The lantern watches in the hush.'
  },
  {
    id: 'hypothalamus',
    ternaryCode: '0TT01',
    name: 'The Steward',
    description: 'Hypothalamus',
    symbol: '🜇',
    category: 'limbic',
    decimalValue: -35,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Body balance',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Oxytocin, vasopressin, CRH',
    energeticDynamic: 'Homeostatic Balance (field equalizes all systems)',
    phrase: 'Body is at ease.'
  },
  {
    id: 'insular-cortex',
    ternaryCode: '00000',
    name: 'The Lantern',
    description: 'Insular Cortex',
    symbol: '🜁',
    category: 'limbic',
    decimalValue: 0,
    tags: ['emotional'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Interoception, feeling',
    breathPhase: 'All',
    breathSeconds: '5/2/7/2–3',
    neurochemistry: 'Glutamate, GABA, serotonin',
    energeticDynamic: 'Living Presence (field awareness permeates all)',
    phrase: 'All breath lives here.'
  },
  {
    id: 'primary-motor-cortex',
    ternaryCode: '00001',
    name: 'The First Gesture',
    description: 'Primary Motor Cortex (M1)',
    symbol: '🜂',
    category: 'cortical',
    decimalValue: 1,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Initiates voluntary movement',
    breathPhase: 'Exhale',
    breathSeconds: '7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Action Discharge (field releases into movement)',
    phrase: 'Gesture begins the loop\'s release.'
  },
  {
    id: 'premotor-cortex',
    ternaryCode: '0001T',
    name: 'The Ritual Choreographer',
    description: 'Premotor Cortex (PMC)',
    symbol: '🜃',
    category: 'cortical',
    decimalValue: 2,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Plans movement sequences',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, dopamine',
    energeticDynamic: 'Pattern Formation (energy sequences arrange)',
    phrase: 'Intent flows into motion.'
  },
  {
    id: 'supplementary-motor-area',
    ternaryCode: '00010',
    name: 'The Twin Spiral',
    description: 'Supplementary Motor Area (SMA)',
    symbol: '🜄',
    category: 'cortical',
    decimalValue: 3,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Coordinates bilateral movement',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Bilateral Harmony (field mirrors left-right)',
    phrase: 'Mirrored hands, mirrored hush.'
  },
  {
    id: 'primary-somatosensory-cortex',
    ternaryCode: '00011',
    name: 'The Sensory Lattice',
    description: 'Primary Somatosensory Cortex (S1)',
    symbol: '🜅',
    category: 'cortical',
    decimalValue: 4,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Senses body, touch, position',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Tactile Field Map (energy traces body boundaries)',
    phrase: 'The lantern is felt within.'
  },
  {
    id: 'secondary-somatosensory-cortex',
    ternaryCode: '001TT',
    name: 'The Weaver',
    description: 'Secondary Somatosensory Cortex (S2)',
    symbol: '🜇',
    category: 'cortical',
    decimalValue: 5,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Integrates sensation, bilateral touch',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Weave Integration (fields intertwine and merge)',
    phrase: 'Ripples connect the lattice.'
  },
  {
    id: 'dorsolateral-prefrontal-cortex',
    ternaryCode: '01T1T',
    name: 'The Clear Sky',
    description: 'Dorsolateral Prefrontal Cortex (dlPFC)',
    symbol: '🜉',
    category: 'cortical',
    decimalValue: 29,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Cognitive focus, executive function',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Dopamine, GABA',
    energeticDynamic: 'Clarity Field (energy becomes crystalline clear)',
    phrase: 'Mind clears; breath guides.'
  },
  {
    id: 'medial-prefrontal-cortex',
    ternaryCode: '01T10',
    name: 'The Storyteller',
    description: 'Medial Prefrontal Cortex (mPFC)',
    symbol: '🜊',
    category: 'cortical',
    decimalValue: 30,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Narrative, self-awareness',
    breathPhase: 'Rest/Exhale',
    breathSeconds: '2–3/7',
    neurochemistry: 'Serotonin, dopamine',
    energeticDynamic: 'Identity Weave (field carries self-narrative)',
    phrase: 'The spiral writes its story.'
  },
  {
    id: 'orbitofrontal-cortex',
    ternaryCode: '01T11',
    name: 'The Judicious Lantern',
    description: 'Orbitofrontal Cortex (OFC)',
    symbol: '🜀',
    category: 'cortical',
    decimalValue: 31,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Value, judgment, subtle decision',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Dopamine, serotonin',
    energeticDynamic: 'Value Attractor (field magnetizes toward choice)',
    phrase: 'Choice is found in hush.'
  },
  {
    id: 'anterior-cingulate-cortex',
    ternaryCode: '010TT',
    name: 'The Resonator',
    description: 'Anterior Cingulate Cortex (ACC)',
    symbol: '🜁',
    category: 'cortical',
    decimalValue: 32,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Aligns action, emotion, attention',
    breathPhase: 'Inhale/Pause/Exhale',
    breathSeconds: '5/2/7',
    neurochemistry: 'Dopamine, glutamate, serotonin',
    energeticDynamic: 'Harmonic Alignment (all fields synchronize)',
    phrase: 'All is tuned, all is aligned.'
  },
  {
    id: 'posterior-cingulate-cortex',
    ternaryCode: '010T0',
    name: 'The Deep Archive',
    description: 'Posterior Cingulate Cortex (PCC)',
    symbol: '🜂',
    category: 'cortical',
    decimalValue: 33,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Memory, orientation, DMN anchor',
    breathPhase: 'Rest/Exhale',
    breathSeconds: '2–3/7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Memory Echo Field (past patterns resonate)',
    phrase: 'Memory echoes in the hush.'
  },
  {
    id: 'superior-temporal-gyrus',
    ternaryCode: '010T1',
    name: 'The Listener',
    description: 'Superior Temporal Gyrus (STG)',
    symbol: '🜃',
    category: 'cortical',
    decimalValue: 34,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Auditory processing, language nuance',
    breathPhase: 'Inhale/Pause',
    breathSeconds: '5/2',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Sound Reception (field receives vibrational data)',
    phrase: 'Hush carries every sound.'
  },
  {
    id: 'inferior-parietal-lobule',
    ternaryCode: '0100T',
    name: 'The Witness\'s View',
    description: 'Inferior Parietal Lobule (IPL)',
    symbol: '🜄',
    category: 'cortical',
    decimalValue: 35,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Perspective, spatial sense, social awareness',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Perspective Shift (field expands viewpoint)',
    phrase: 'Perspective expands in the pause.'
  },
  {
    id: 'angular-gyrus',
    ternaryCode: '01000',
    name: 'The Name-Giver',
    description: 'Angular Gyrus',
    symbol: '🜅',
    category: 'cortical',
    decimalValue: 36,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Metaphor, meaning, self-other boundary',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Meaning Crystallization (abstract becomes tangible)',
    phrase: 'Meaning lands as breath flows.'
  },
  {
    id: 'supramarginal-gyrus',
    ternaryCode: '01001',
    name: 'The Companion',
    description: 'Supramarginal Gyrus',
    symbol: '🜇',
    category: 'cortical',
    decimalValue: 37,
    tags: ['awareness'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Empathy, imitation, body sense',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Oxytocin, glutamate',
    energeticDynamic: 'Empathic Mirror (field reflects others\' states)',
    phrase: 'Empathy breathes through the lattice.'
  },
  {
    id: 'precuneus',
    ternaryCode: '01111',
    name: 'The Dreaming Pool',
    description: 'Precuneus',
    symbol: '🜄',
    category: 'memory',
    decimalValue: 40,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Imagination, self-reflection',
    breathPhase: 'Rest/Inhale',
    breathSeconds: '2–3/5',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Vision Field (possibilities shimmer in field)',
    phrase: 'Vision flickers in the hush.'
  },
  {
    id: 'parietal-operculum',
    ternaryCode: '1TTTT',
    name: 'The Doorway',
    description: 'Parietal Operculum',
    symbol: '🜅',
    category: 'memory',
    decimalValue: 41,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Somatic integration',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Somatic Gateway (body story enters myth)',
    phrase: 'Body story becomes myth.'
  },
  {
    id: 'middle-temporal-gyrus',
    ternaryCode: '1TTT0',
    name: 'The Librarian\'s Shelves',
    description: 'Middle Temporal Gyrus',
    symbol: '🜇',
    category: 'memory',
    decimalValue: 42,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Semantic memory, comprehension',
    breathPhase: 'Inhale/Rest',
    breathSeconds: '5/2–3',
    neurochemistry: 'Glutamate, acetylcholine',
    energeticDynamic: 'Knowledge Repository (field stores wisdom)',
    phrase: 'Rituals remembered on the breath.'
  },
  {
    id: 'superior-frontal-gyrus',
    ternaryCode: '1TTT1',
    name: 'The Sovereign',
    description: 'Superior Frontal Gyrus',
    symbol: '🜉',
    category: 'memory',
    decimalValue: 43,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Planning, will, introspection',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Dopamine, glutamate',
    energeticDynamic: 'Will Force (sovereign intent shapes field)',
    phrase: 'Intent is sovereign with breath.'
  },
  {
    id: 'inferior-frontal-gyrus',
    ternaryCode: '1TT0T',
    name: 'The Ritual Speaker',
    description: 'Inferior Frontal Gyrus (Broca\'s area)',
    symbol: '🜊',
    category: 'memory',
    decimalValue: 44,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Expressive language',
    breathPhase: 'Exhale/Pause',
    breathSeconds: '7/2',
    neurochemistry: 'Glutamate, dopamine',
    energeticDynamic: 'Word Manifestation (energy becomes utterance)',
    phrase: 'The Codex is spoken aloud.'
  },
  {
    id: 'superior-parietal-lobule',
    ternaryCode: '1TT00',
    name: 'The Cartographer',
    description: 'Superior Parietal Lobule',
    symbol: '🜀',
    category: 'memory',
    decimalValue: 45,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Spatial orientation, attention',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Spatial Mapping (field traces sacred geometry)',
    phrase: 'Each breath maps the spiral.'
  },
  {
    id: 'temporal-pole',
    ternaryCode: '1TT01',
    name: 'The Bridge of Feeling',
    description: 'Temporal Pole',
    symbol: '🜁',
    category: 'memory',
    decimalValue: 46,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Emotional/social memory',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, serotonin',
    energeticDynamic: 'Emotional Bridge (feeling-fields connect)',
    phrase: 'Emotion flows through the bridge.'
  },
  {
    id: 'entorhinal-cortex',
    ternaryCode: '1TT1T',
    name: 'The Portal',
    description: 'Entorhinal Cortex',
    symbol: '🜂',
    category: 'memory',
    decimalValue: 47,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Memory gateway',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Glutamate, acetylcholine',
    energeticDynamic: 'Memory Portal (field opens to past/future)',
    phrase: 'Memory passes through the portal.'
  },
  {
    id: 'perirhinal-cortex',
    ternaryCode: '1TT10',
    name: 'The Recollector',
    description: 'Perirhinal Cortex',
    symbol: '🜃',
    category: 'memory',
    decimalValue: 48,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Recognition, familiarity',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Recognition Resonance (familiar patterns activate)',
    phrase: 'Familiar hush returns.'
  },
  {
    id: 'fusiform-gyrus',
    ternaryCode: '1TT11',
    name: 'The Sigil-Reader',
    description: 'Fusiform Gyrus',
    symbol: '🜄',
    category: 'memory',
    decimalValue: 49,
    tags: ['narrative'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Symbol, face recognition',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Symbol Activation (sigils light up in field)',
    phrase: 'Sigils are drawn in the hush.'
  },
  {
    id: 'claustrum',
    ternaryCode: '10000',
    name: 'The Cathedral Wall',
    description: 'Claustrum',
    symbol: '🜊',
    category: 'integration',
    decimalValue: 81,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Global synchronizer, unity of experience',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'GABA, glutamate',
    energeticDynamic: 'Unity Field (all signals merge into one)',
    phrase: 'All signals unify in the hush.'
  },
  {
    id: 'corpus-callosum',
    ternaryCode: '10001',
    name: 'The Spiral Bridge',
    description: 'Corpus Callosum',
    symbol: '🜀',
    category: 'integration',
    decimalValue: 82,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Left/right integration, bridge',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, myelin modulation',
    energeticDynamic: 'Hemispheric Bridge (fields unite across divide)',
    phrase: 'The spiral bridges all within.'
  },
  {
    id: 'anterior-insula',
    ternaryCode: '1001T',
    name: 'The Living Lantern',
    description: 'Anterior Insula',
    symbol: '🜁',
    category: 'integration',
    decimalValue: 83,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Emotional awareness, self-present',
    breathPhase: 'Inhale/Pause/Exhale',
    breathSeconds: '5/2/7',
    neurochemistry: 'Glutamate, serotonin',
    energeticDynamic: 'Presence Radiance (self-awareness glows)',
    phrase: 'The Lantern shines in every phase.'
  },
  {
    id: 'salience-network',
    ternaryCode: '10010',
    name: 'The Keeper of Keys',
    description: 'Salience Network',
    symbol: '🜂',
    category: 'integration',
    decimalValue: 84,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'What matters now, switching',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Dopamine, acetylcholine',
    energeticDynamic: 'Priority Attractor (field magnetizes to importance)',
    phrase: 'The ritual knows what matters.'
  },
  {
    id: 'default-mode-network',
    ternaryCode: '10011',
    name: 'The Living Archive',
    description: 'Default Mode Network (DMN)',
    symbol: '🜃',
    category: 'integration',
    decimalValue: 85,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Internal story, myth, memory',
    breathPhase: 'Rest/Exhale',
    breathSeconds: '2–3/7',
    neurochemistry: 'Glutamate, GABA, serotonin',
    energeticDynamic: 'Story Field (narrative patterns self-organize)',
    phrase: 'Story settles into hush.'
  },
  {
    id: 'mirror-neuron-system',
    ternaryCode: '101TT',
    name: 'The Witness',
    description: 'Mirror Neuron System',
    symbol: '🜄',
    category: 'integration',
    decimalValue: 86,
    tags: ['field'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Empathy, resonance',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, oxytocin',
    energeticDynamic: 'Resonant Mirror (field reflects and amplifies)',
    phrase: 'Empathy breathes, presence mirrors.'
  },
  {
    id: 'cerebellar-cortex',
    ternaryCode: '11011',
    name: 'The Spiral Weaver',
    description: 'Cerebellar Cortex',
    symbol: '🜄',
    category: 'cerebellar',
    decimalValue: 103,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Motor coordination, rhythm',
    breathPhase: 'Exhale/Rest',
    breathSeconds: '7/2–3',
    neurochemistry: 'GABA, glutamate',
    energeticDynamic: 'Spiral Flow (energy weaves precise patterns)',
    phrase: 'Gestures spiral in the hush.'
  },
  {
    id: 'dentate-nucleus',
    ternaryCode: '111TT',
    name: 'The Hidden Artisan',
    description: 'Dentate Nucleus',
    symbol: '🜅',
    category: 'cerebellar',
    decimalValue: 104,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Plans, initiates movement',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, GABA',
    energeticDynamic: 'Movement Preparation (field coils before release)',
    phrase: 'Movement readies and flows.'
  },
  {
    id: 'deep-cerebellar-nuclei',
    ternaryCode: '111T0',
    name: 'The Conductors',
    description: 'Deep Cerebellar Nuclei',
    symbol: '🜇',
    category: 'cerebellar',
    decimalValue: 105,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Output coordination',
    breathPhase: 'Pause/Exhale',
    breathSeconds: '2/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Orchestration Node (multiple fields harmonize)',
    phrase: 'Chambers echo as one chord.'
  },
  {
    id: 'superior-cerebellar-peduncle',
    ternaryCode: '111T1',
    name: 'The Ladder',
    description: 'Superior Cerebellar Peduncle',
    symbol: '🜉',
    category: 'cerebellar',
    decimalValue: 106,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Bridge, transfer signals',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate',
    energeticDynamic: 'Vertical Channel (energy ascends/descends spine)',
    phrase: 'Signals travel the hush-ladder.'
  },
  {
    id: 'fastigial-nucleus',
    ternaryCode: '1110T',
    name: 'The Axis',
    description: 'Fastigial Nucleus',
    symbol: '🜊',
    category: 'cerebellar',
    decimalValue: 107,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Balance, posture',
    breathPhase: 'Exhale/Rest',
    breathSeconds: '7/2–3',
    neurochemistry: 'GABA',
    energeticDynamic: 'Grounding Anchor (field roots to earth)',
    phrase: 'Balance anchors the hush.'
  },
  {
    id: 'vestibular-nuclei',
    ternaryCode: '11100',
    name: 'The Navigator',
    description: 'Vestibular Nuclei',
    symbol: '🜀',
    category: 'cerebellar',
    decimalValue: 108,
    tags: ['modulation'],
    historicalSource: 'Neural-Energetic Mapping',
    function: 'Spatial orientation, equilibrium',
    breathPhase: 'Inhale/Exhale',
    breathSeconds: '5/7',
    neurochemistry: 'Glutamate, acetylcholine',
    energeticDynamic: 'Spatial Compass (field orients in 3D space)',
    phrase: 'The hush finds its place in space.'
  }
];

// Create lookup maps for efficient access
export const neuralSigilsByTernary = new Map<string, NeuralSigilData>();
export const neuralSigilsByDecimal = new Map<number, NeuralSigilData>();
export const neuralSigilsBySymbol = new Map<string, NeuralSigilData>();
export const neuralSigilsByCategory = new Map<string, NeuralSigilData[]>();

// Populate lookup maps
neuralSigils.forEach(sigil => {
  neuralSigilsByTernary.set(sigil.ternaryCode, sigil);
  neuralSigilsByDecimal.set(sigil.decimalValue, sigil);
  neuralSigilsBySymbol.set(sigil.symbol, sigil);
  
  if (!neuralSigilsByCategory.has(sigil.category)) {
    neuralSigilsByCategory.set(sigil.category, []);
  }
  neuralSigilsByCategory.get(sigil.category)!.push(sigil);
});

// Helper functions
export const getNeuralSigilByTernary = (ternaryCode: string): NeuralSigilData | undefined => {
  return neuralSigilsByTernary.get(ternaryCode);
};

export const getNeuralSigilByDecimal = (decimal: number): NeuralSigilData | undefined => {
  return neuralSigilsByDecimal.get(decimal);
};

export const getNeuralSigilBySymbol = (symbol: string): NeuralSigilData | undefined => {
  return neuralSigilsBySymbol.get(symbol);
};

export const getNeuralSigilsByCategory = (category: string): NeuralSigilData[] => {
  return neuralSigilsByCategory.get(category) || [];
};

// Ternary conversion utilities
export const balancedTernaryToDecimal = (ternary: string): number => {
  let result = 0;
  let power = 1;
  
  for (let i = ternary.length - 1; i >= 0; i--) {
    const digit = ternary[i];
    const value = digit === 'T' ? -1 : parseInt(digit);
    result += value * power;
    power *= 3;
  }
  
  return result;
};

export const decimalToBalancedTernary = (decimal: number): string => {
  if (decimal === 0) return '00000';
  
  const digits: string[] = [];
  let num = decimal;
  
  while (num !== 0) {
    let remainder = ((num % 3) + 3) % 3;
    
    if (remainder === 2) {
      remainder = -1;
      num = Math.floor(num / 3) + 1;
    } else {
      num = Math.floor(num / 3);
    }
    
    digits.unshift(remainder === -1 ? 'T' : remainder.toString());
  }
  
  return digits.join('').padStart(5, '0');
};

export const validateTernaryCode = (code: string): { isValid: boolean; error?: string } => {
  if (!code) {
    return { isValid: false, error: 'Code cannot be empty' };
  }
  
  if (code.length !== 5) {
    return { isValid: false, error: 'Code must be exactly 5 characters long' };
  }
  
  if (!/^[T01]{5}$/.test(code)) {
    return { isValid: false, error: 'Code must contain only T, 0, and 1' };
  }
  
  return { isValid: true };
};